spring.application.name=restapi
logging.level.root=ERROR
logging.level.com.example.restapi=INFO
server.url=https://api.restful-api.dev/objects
# server.url=https://api.restful-api.dev/collections/products/objects
server.api-key=e673bc9b-6309-42e0-bb7a-5bfa941ef207